### ISSUE TITLE
compile code in linux getting error 

### ISSUE THREAD

**Issue by mithkum** [coin-worx/coin-exchange-backend#15]
xbuild CoinExchange.sln 
XBuild Engine Version 12.0
Mono, Version 4.2.1.0
Copyright (C) 2005-2013 Various Mono authors

Build started 23-07-2018 16:35:01.
__________________________________________________
Project "/var/www/git/coin-exchange-backend/src/CoinExchange.sln" (default target(s)):
	Target ValidateSolutionConfiguration:
		Building solution configuration "Debug|Any CPU".
	Target Build:
		Project "/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Port.Adapter.Messaging/CoinExchange.Trades.Port.Adapter.Messaging.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Port.Adapter.Messaging/CoinExchange.Trades.Port.Adapter.Messaging.csproj".
		Project "/var/www/git/coin-exchange-backend/src/Funds/CoinExchange.Funds.Infrastructure.Common/CoinExchange.Funds.Infrastructure.Common.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/Funds/CoinExchange.Funds.Infrastructure.Common/CoinExchange.Funds.Infrastructure.Common.csproj".
		Project "/var/www/git/coin-exchange-backend/src/Funds/CoinExchange.Funds.Port.Adapter.Messaging/CoinExchange.Funds.Port.Adapter.Messaging.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/Funds/CoinExchange.Funds.Port.Adapter.Messaging/CoinExchange.Funds.Port.Adapter.Messaging.csproj".
		Project "/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common/CoinExchange.Common.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common/CoinExchange.Common.csproj".
		Project "/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Port.Adapter.Rest.Tests/CoinExchange.Trades.Port.Adapter.Rest.Tests.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target ResolveAssemblyReferences:
/usr/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets:  warning : Reference 'Microsoft.VisualStudio.QualityTools.UnitTestFramework' not resolved
				For searchpath {CandidateAssemblyFiles}
				Warning: {CandidateAssemblyFiles} not supported currently
				For searchpath /Common Files/microsoft shared/VSTT/10.0/UITestExtensionPackages
				Considered '/Common Files/microsoft shared/VSTT/10.0/UITestExtensionPackages/Microsoft.VisualStudio.QualityTools.UnitTestFramework' as a file, but the file does not exist
				Considered '/Common Files/microsoft shared/VSTT/10.0/UITestExtensionPackages/Microsoft.VisualStudio.QualityTools.UnitTestFramework.exe' as a file, but the file does not exist
				Considered '/Common Files/microsoft shared/VSTT/10.0/UITestExtensionPackages/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll' as a file, but the file does not exist
				For searchpath {HintPathFromItem}
				HintPath attribute not found
				For searchpath {TargetFrameworkDirectory}
				Considered target framework dir /usr/lib/mono/4.5, assembly named 'Microsoft.VisualStudio.QualityTools.UnitTestFramework' not found.
				Considered target framework dir /usr/lib/mono/4.5/Facades/, assembly named 'Microsoft.VisualStudio.QualityTools.UnitTestFramework' not found.
				For searchpath {PkgConfig}
				Considered Microsoft.VisualStudio.QualityTools.UnitTestFramework, but could not find in any pkg-config files.
				For searchpath {GAC}
				Considered Microsoft.VisualStudio.QualityTools.UnitTestFramework, but could not find in the GAC.
				For searchpath {RawFileName}
				Considered 'Microsoft.VisualStudio.QualityTools.UnitTestFramework' as a file, but the file does not exist
				For searchpath bin/Debug/
				Considered '/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Port.Adapter.Rest.Tests/bin/Debug/Microsoft.VisualStudio.QualityTools.UnitTestFramework' as a file, but the file does not exist
				Considered '/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Port.Adapter.Rest.Tests/bin/Debug/Microsoft.VisualStudio.QualityTools.UnitTestFramework.exe' as a file, but the file does not exist
				Considered '/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Port.Adapter.Rest.Tests/bin/Debug/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll' as a file, but the file does not exist
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Port.Adapter.Rest.Tests/CoinExchange.Trades.Port.Adapter.Rest.Tests.csproj".
		Project "/var/www/git/coin-exchange-backend/src/Client/CoinExchange.Client/CoinExchange.Client.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/Client/CoinExchange.Client/CoinExchange.Client.csproj".
		Project "/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/CoinExchange.Common.Tests.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target ResolveAssemblyReferences:
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'MySql.Data, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' not resolved
				For searchpath {CandidateAssemblyFiles}
				Warning: {CandidateAssemblyFiles} not supported currently
				For searchpath {HintPathFromItem}
				Considered ../../../../../Program Files (x86)/MySQL/MySQL Connector Net 6.8.3/Assemblies/v4.5/MySql.Data.dll, but it does not exist.
				For searchpath {TargetFrameworkDirectory}
				Considered target framework dir /usr/lib/mono/4.5, assembly named 'MySql.Data' not found.
				Considered target framework dir /usr/lib/mono/4.5/Facades/, assembly named 'MySql.Data' not found.
				For searchpath {PkgConfig}
				Considered MySql.Data, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL, but could not find in any pkg-config files.
				For searchpath {GAC}
				Considered MySql.Data, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL, but could not find in the GAC.
				For searchpath {RawFileName}
				Considered 'MySql.Data, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' as a file, but the file does not exist
				For searchpath bin/Debug/
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Data' as a file, but the file does not exist
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Data.exe' as a file, but the file does not exist
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Data.dll' as a file, but the file does not exist
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'MySql.Data.Entity.EF5, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' not resolved
				For searchpath {CandidateAssemblyFiles}
				Warning: {CandidateAssemblyFiles} not supported currently
				For searchpath {HintPathFromItem}
				Considered ../../../../../Program Files (x86)/MySQL/MySQL Connector Net 6.8.3/Assemblies/v4.5/MySql.Data.Entity.EF5.dll, but it does not exist.
				For searchpath {TargetFrameworkDirectory}
				Considered target framework dir /usr/lib/mono/4.5, assembly named 'MySql.Data.Entity.EF5' not found.
				Considered target framework dir /usr/lib/mono/4.5/Facades/, assembly named 'MySql.Data.Entity.EF5' not found.
				For searchpath {PkgConfig}
				Considered MySql.Data.Entity.EF5, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL, but could not find in any pkg-config files.
				For searchpath {GAC}
				Considered MySql.Data.Entity.EF5, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL, but could not find in the GAC.
				For searchpath {RawFileName}
				Considered 'MySql.Data.Entity.EF5, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' as a file, but the file does not exist
				For searchpath bin/Debug/
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Data.Entity.EF5' as a file, but the file does not exist
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Data.Entity.EF5.exe' as a file, but the file does not exist
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Data.Entity.EF5.dll' as a file, but the file does not exist
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'MySql.Data.Entity.EF6, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' not resolved
				For searchpath {CandidateAssemblyFiles}
				Warning: {CandidateAssemblyFiles} not supported currently
				For searchpath {HintPathFromItem}
				Considered ../../../../../Program Files (x86)/MySQL/MySQL Connector Net 6.8.3/Assemblies/v4.5/MySql.Data.Entity.EF6.dll, but it does not exist.
				For searchpath {TargetFrameworkDirectory}
				Considered target framework dir /usr/lib/mono/4.5, assembly named 'MySql.Data.Entity.EF6' not found.
				Considered target framework dir /usr/lib/mono/4.5/Facades/, assembly named 'MySql.Data.Entity.EF6' not found.
				For searchpath {PkgConfig}
				Considered MySql.Data.Entity.EF6, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL, but could not find in any pkg-config files.
				For searchpath {GAC}
				Considered MySql.Data.Entity.EF6, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL, but could not find in the GAC.
				For searchpath {RawFileName}
				Considered 'MySql.Data.Entity.EF6, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' as a file, but the file does not exist
				For searchpath bin/Debug/
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Data.Entity.EF6' as a file, but the file does not exist
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Data.Entity.EF6.exe' as a file, but the file does not exist
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Data.Entity.EF6.dll' as a file, but the file does not exist
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'MySql.Web, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' not resolved
				For searchpath {CandidateAssemblyFiles}
				Warning: {CandidateAssemblyFiles} not supported currently
				For searchpath {HintPathFromItem}
				Considered ../../../../../Program Files (x86)/MySQL/MySQL Connector Net 6.8.3/Assemblies/v4.5/MySql.Web.dll, but it does not exist.
				For searchpath {TargetFrameworkDirectory}
				Considered target framework dir /usr/lib/mono/4.5, assembly named 'MySql.Web' not found.
				Considered target framework dir /usr/lib/mono/4.5/Facades/, assembly named 'MySql.Web' not found.
				For searchpath {PkgConfig}
				Considered MySql.Web, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL, but could not find in any pkg-config files.
				For searchpath {GAC}
				Considered MySql.Web, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL, but could not find in the GAC.
				For searchpath {RawFileName}
				Considered 'MySql.Web, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' as a file, but the file does not exist
				For searchpath bin/Debug/
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Web' as a file, but the file does not exist
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Web.exe' as a file, but the file does not exist
				Considered '/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/bin/Debug/MySql.Web.dll' as a file, but the file does not exist
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/CoinExchange.Common.Tests.csproj".
		Project "/var/www/git/coin-exchange-backend/src/IdentityAccess/CoinExchange.IdentityAccess.Infrastructure/CoinExchange.IdentityAccess.Infrastructure.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/IdentityAccess/CoinExchange.IdentityAccess.Infrastructure/CoinExchange.IdentityAccess.Infrastructure.csproj".
		Project "/var/www/git/coin-exchange-backend/src/IdentityAccess/CoinExchange.IdentityAccess.Port.Adapter.Messaging/CoinExchange.IdentityAccess.Port.Adapter.Messaging.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/IdentityAccess/CoinExchange.IdentityAccess.Port.Adapter.Messaging/CoinExchange.IdentityAccess.Port.Adapter.Messaging.csproj".
		Project "/var/www/git/coin-exchange-backend/src/IdentityAccess/CoinExchange.IdentityAccess.Port.Adapter.Rest.Tests/CoinExchange.IdentityAccess.Port.Adapter.Rest.Tests.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/IdentityAccess/CoinExchange.IdentityAccess.Port.Adapter.Rest.Tests/CoinExchange.IdentityAccess.Port.Adapter.Rest.Tests.csproj".
		Project "/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Infrastructure.Services.IntegrationTests/CoinExchange.Trades.Infrastructure.Services.IntegrationTests.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Infrastructure.Services.IntegrationTests/CoinExchange.Trades.Infrastructure.Services.IntegrationTests.csproj".
		Project "/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Domain.Model/CoinExchange.Trades.Domain.Model.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
				Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/CoinExchange.Trades.Domain.Model.dll CurrencyPairAggregate/CurrencyPair.cs CurrencyPairAggregate/ICurrencyPairRepository.cs OrderMatchingEngine/BBOEvent.cs OrderMatchingEngine/DepthEvent.cs OrderMatchingEngine/ExchangeEssentials.cs OrderMatchingEngine/ExchangeEssentialsSnapshortEvent.cs OrderMatchingEngine/LimitOrderBookEvent.cs OrderAggregate/OrderEvent.cs OrderMatchingEngine/ExchangeEssentialsList.cs OrderMatchingEngine/LimitOrderBookReplayService.cs OrderMatchingEngine/ReplayService.cs Services/IBalanceValidationService.cs TradeAggregate/ITradeIdGenerator.cs TradeAggregate/TradeEvent.cs OrderAggregate/InputDisruptorPublisher.cs OrderAggregate/InputPayload.cs OrderAggregate/OrderCancellation.cs OrderMatchingEngine/BBO.cs OrderMatchingEngine/BBOListener.cs OrderMatchingEngine/ChangeId.cs OrderMatchingEngine/Depth.cs OrderMatchingEngine/DepthLevel.cs OrderMatchingEngine/DepthLevelMap.cs OrderMatchingEngine/DepthListener.cs OrderMatchingEngine/DepthOrderBook.cs OrderMatchingEngine/Exchange.cs OrderMatchingEngine/FillFlags.cs OrderMatchingEngine/IBBOListener.cs OrderMatchingEngine/IDepthListener.cs OrderMatchingEngine/IOrderBookListener.cs OrderMatchingEngine/IOrderListener.cs OrderMatchingEngine/ITradeListener.cs OrderMatchingEngine/LimitOrderBook.cs OrderMatchingEngine/OrderBookListener.cs OrderMatchingEngine/OrderList.cs OrderMatchingEngine/OrderListener.cs OrderMatchingEngine/TradeListener.cs OrderMatchingEngine/Types.cs OrderAggregate/Order.cs OrderAggregate/OrderFactory.cs OrderAggregate/OrderSide.cs OrderAggregate/OrderStatus.cs OrderAggregate/OrderType.cs OrderAggregate/Price.cs OrderAggregate/Volume.cs Properties/AssemblyInfo.cs OrderAggregate/CancelOrderResponse.cs MarketDataAggregate/MarketData.cs MarketDataAggregate/Ohlc.cs OrderAggregate/OrderId.cs OrderAggregate/TradeRecord.cs Services/IEventStore.cs Services/IOrderIdGenerator.cs Services/Journaler.cs Services/OutputDisruptor.cs TradeAggregate/Trade.cs TradeAggregate/TradeExecutedEvent.cs TradeAggregate/TradeFactory.cs TradeAggregate/TradeId.cs TradeAggregate/TradeList.cs TradeAggregate/TraderId.cs /target:library /define:"DEBUG;TRACE" /nostdlib /reference:../../packages/Disruptor.1.1.0/lib/net40/Atomic.dll /reference:../../packages/Common.Logging.2.1.2/lib/net40/Common.Logging.dll /reference:../../packages/Disruptor.1.1.0/lib/net40/Disruptor.dll /reference:../../packages/Disruptor.1.1.0/lib/net40/Disruptor.Scheduler.dll /reference:../../packages/log4net.1.2.10/lib/2.0/log4net.dll /reference:../../packages/Newtonsoft.Json.6.0.4/lib/net45/Newtonsoft.Json.dll /reference:../../packages/Spring.Aop.1.3.2/lib/net40/Spring.Aop.dll /reference:../../packages/Spring.Core.1.3.2/lib/net40/Spring.Core.dll /reference:../../packages/Spring.Data.1.3.2/lib/net40/Spring.Data.dll /reference:../../packages/Spring.Web.2.0.0-RC1/lib/net45/Spring.Web.dll /reference:../../packages/Spring.Web.Mvc4.2.0.0-RC1/lib/net45/Spring.Web.Mvc4.dll /reference:/usr/lib/mono/4.5/System.dll /reference:/usr/lib/mono/4.5/System.Runtime.Serialization.dll /reference:/usr/lib/mono/4.5/System.Xml.Linq.dll /reference:/usr/lib/mono/4.5/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/4.5/Microsoft.CSharp.dll /reference:/usr/lib/mono/4.5/System.Data.dll /reference:/usr/lib/mono/4.5/System.Xml.dll /reference:/usr/lib/mono/4.5/System.Core.dll /reference:/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common/bin/Debug//CoinExchange.Common.dll /reference:/usr/lib/mono/4.5/mscorlib.dll /warn:4
CSC: error CS1705: Assembly `Spring.Web, Version=2.0.0.45000, Culture=neutral, PublicKeyToken=65e474d141e25e07' references `Spring.Core, Version=2.0.0.45000, Culture=neutral, PublicKeyToken=65e474d141e25e07' which has a higher version number than imported assembly `Spring.Core, Version=1.3.2.40943, Culture=neutral, PublicKeyToken=65e474d141e25e07'
			Task "Csc" execution -- FAILED
			Done building target "CoreCompile" in project "/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Domain.Model/CoinExchange.Trades.Domain.Model.csproj".-- FAILED
		Done building project "/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Domain.Model/CoinExchange.Trades.Domain.Model.csproj".-- FAILED
		Project "/var/www/git/coin-exchange-backend/src/Funds/CoinExchange.Funds.Domain.Model/CoinExchange.Funds.Domain.Model.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
			Target _CopyDeployFilesToOutputDirectoryAlways:
				Copying file from '/var/www/git/coin-exchange-backend/src/Funds/CoinExchange.Funds.Domain.Model/FundsDomainModelConfig.xml' to '/var/www/git/coin-exchange-backend/src/Funds/CoinExchange.Funds.Domain.Model/bin/Debug/FundsDomainModelConfig.xml'
		Done building project "/var/www/git/coin-exchange-backend/src/Funds/CoinExchange.Funds.Domain.Model/CoinExchange.Funds.Domain.Model.csproj".
		Project "/var/www/git/coin-exchange-backend/src/IdentityAccess/CoinExchange.IdentityAccess.Domain.Model/CoinExchange.IdentityAccess.Domain.Model.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target GenerateTargetFrameworkMonikerAttribute:
			Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/var/www/git/coin-exchange-backend/src/IdentityAccess/CoinExchange.IdentityAccess.Domain.Model/CoinExchange.IdentityAccess.Domain.Model.csproj".
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/var/www/git/coin-exchange-backend/src/CoinExchange.sln".-- FAILED
Done building project "/var/www/git/coin-exchange-backend/src/CoinExchange.sln".-- FAILED

Build FAILED.

Warnings:

/var/www/git/coin-exchange-backend/src/CoinExchange.sln (default targets) ->
(Build target) ->
/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Port.Adapter.Rest.Tests/CoinExchange.Trades.Port.Adapter.Rest.Tests.csproj (default targets) ->
/usr/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

	/usr/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets:  warning : Reference 'Microsoft.VisualStudio.QualityTools.UnitTestFramework' not resolved

/var/www/git/coin-exchange-backend/src/CoinExchange.sln (default targets) ->
(Build target) ->
/var/www/git/coin-exchange-backend/src/Common/CoinExchange.Common.Tests/CoinExchange.Common.Tests.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'MySql.Data, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' not resolved
	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'MySql.Data.Entity.EF5, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' not resolved
	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'MySql.Data.Entity.EF6, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' not resolved
	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'MySql.Web, Version=6.8.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL' not resolved

Errors:

/var/www/git/coin-exchange-backend/src/CoinExchange.sln (default targets) ->
(Build target) ->
/var/www/git/coin-exchange-backend/src/Trades/CoinExchange.Trades.Domain.Model/CoinExchange.Trades.Domain.Model.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	CSC: error CS1705: Assembly `Spring.Web, Version=2.0.0.45000, Culture=neutral, PublicKeyToken=65e474d141e25e07' references `Spring.Core, Version=2.0.0.45000, Culture=neutral, PublicKeyToken=65e474d141e25e07' which has a higher version number than imported assembly `Spring.Core, Version=1.3.2.40943, Culture=neutral, PublicKeyToken=65e474d141e25e07'

	 5 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:05.8636320

![screenshot from 2018-07-23 16-36-21](https://user-images.githubusercontent.com/12783321/43073273-93b8a54a-8e96-11e8-8475-83e27ba8fce2.png)

Please suggest me solution

**Comment by abaziz** [comment]
Hello @mithkum 

We haven't tested this code in linux. Currently we don't have the resources as part of the open source project to test it out. We'll get back once we have the availability.

Thanks

**Comment by mithkum** [comment]
Hi @abaziz,

Now , I am getting new error in VS please check the snapshot 
![imgpsh_fullsize](https://user-images.githubusercontent.com/12783321/43460997-e7b85258-94ef-11e8-99d7-90473f5a40d3.png)

Please suggest me solution , I am waiting for your positive response .

Thanks

**Comment by TaimoorChoudhary** [comment]
Hi @mithkum 

Please go through the ReadMe file and setup Bitcoin and Litecoin testnets on your machine. This error indicates that the Bitcoin testnet is not running on your machine.

Thanks.

**Comment by TaimoorChoudhary** [comment]
Closing this issue as the backend application ran successfully.

**Comment by mithkum** [comment]
@TaimoorChoudhary ok , thanks for confirm
